root: data/ASVspoof2019_LA

train:
  _target_: src.datasets.ASVspoofDataset
  root: ${datasets.root}
  part: train
  sample_rate: 16000
  n_fft: 1724
  win_length: 1724
  hop_length: 130
  target_frames: 600
  max_items_per_label: null
  random_crop: true
  limit: null
  shuffle_index: true

dev:
  _target_: src.datasets.ASVspoofDataset
  root: ${datasets.root}
  part: dev
  sample_rate: 16000
  n_fft: 1724
  win_length: 1724
  hop_length: 130
  target_frames: 600
  max_items_per_label: null
  random_crop: false
  limit: null
  shuffle_index: false
