root: data/ASVspoof2019_LA

train:
  _target_: src.datasets.ASVspoofDataset
  root: ${datasets.root}
  part: train
  sample_rate: 16000
  n_fft: 1724
  win_length: 1724
  hop_length: 130
  target_frames: 600
  random_crop: false
  limit: 8
  shuffle_index: false

dev:
  _target_: src.datasets.ASVspoofDataset
  root: ${datasets.root}
  part: train
  sample_rate: 16000
  n_fft: 1724
  win_length: 1724
  hop_length: 130
  target_frames: 600
  random_crop: false
  limit: 8
  shuffle_index: false
