defaults:
  - model: lcnn
  - writer: wandb
  - metrics: asvspoof
  - datasets: asvspoof
  - dataloader: audio
  - transforms: asvspoof
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 3.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8

lr_scheduler: null

loss_function:
  _target_: src.loss.CrossEntropyLossWrapper

trainer:
  log_step: 50
  n_epochs: 50
  epoch_len: null
  device_tensors: ["features", "labels"]
  resume_from: null
  from_pretrained: null
  device: auto
  override: False
  monitor: "min dev_EER"
  save_period: 5
  early_stop: 15
  save_dir: "saved"
  seed: 42
  max_grad_norm: 5
