defaults:
  - model: stc_lcnn
  - writer: wandb
  - metrics: asvspoof
  - datasets: asvspoof_recipe
  - dataloader: audio
  - transforms: asvspoof
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 3.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 10
  gamma: 0.5

loss_function:
  _target_: src.loss.CrossEntropyLossWrapper

trainer:
  log_step: 100
  n_epochs: 30
  epoch_len: null
  device_tensors: ["features", "labels"]
  resume_from: null
  from_pretrained: null
  device: auto
  override: False
  monitor: "min dev_EER"
  save_period: 1
  early_stop: 10
  save_dir: "saved"
  seed: 42
  max_grad_norm: 5
  scheduler_step: epoch
