defaults:
  - model: lcnn
  - writer: wandb
  - metrics: asvspoof
  - datasets: asvspoof_one_batch
  - dataloader: audio
  - transforms: asvspoof
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 3.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8

lr_scheduler: null

loss_function:
  _target_: src.loss.CrossEntropyLossWrapper

trainer:
  log_step: 1
  n_epochs: 100
  epoch_len: 20
  device_tensors: ["features", "labels"]
  resume_from: null
  from_pretrained: null
  device: auto
  override: False
  monitor: "min dev_EER"
  save_period: 10
  early_stop: 100
  save_dir: "saved"
  seed: 42
  max_grad_norm: 5
